from recipe_model import Recipe

RECIPES = {
    "pizza": Recipe("Pizza", 15, 220),
    "lasagne": Recipe("Lasagne", 30, 180),
    "kekse": Recipe("Kekse", 12, 160),
    "pommes": Recipe("Pommes", 25, 200),
    "chicken nuggets": Recipe("Chicken Nuggets", 15, 200),
    "fischstäbchen": Recipe("Fischstäbchen", 12, 200),
    "brötchen": Recipe("Brötchen", 10, 180),
    "croissant": Recipe("Croissant", 15, 180),
    "baguette": Recipe("Baguette", 12, 200),
    "brot": Recipe("Brot", 45, 220),
    "muffins": Recipe("Muffins", 25, 180),
    "brownies": Recipe("Brownies", 30, 180),
    "apfelkuchen": Recipe("Apfelkuchen", 50, 180),
    "käsekuchen": Recipe("Käsekuchen", 60, 170),
    "franzbrötchen": Recipe("Franzbrötchen", 20, 180),
    "ofenkartoffeln": Recipe("Ofenkartoffeln", 45, 200),
    "kartoffelgratin": Recipe("Kartoffelgratin", 50, 180),
    "auflauf": Recipe("Auflauf", 35, 180),
    "cannelloni": Recipe("Cannelloni", 35, 180),
    "mac and cheese": Recipe("Mac and Cheese", 25, 180),
    "hähnchenbrust": Recipe("Hähnchenbrust", 25, 200),
    "hähnchenschenkel": Recipe("Hähnchenschenkel", 40, 200),
    "lachs": Recipe("Lachs", 20, 180),
    "pizza brötchen": Recipe("Pizza Brötchen", 12, 200),
    "mozzarella sticks": Recipe("Mozzarella Sticks", 10, 200),
    "onion rings": Recipe("Onion Rings", 12, 200),
    "nachos": Recipe("Nachos", 8, 180),
    "pizzaschnecken": Recipe("Pizzaschnecken", 20, 180),
    "quiche": Recipe("Quiche", 40, 180),
    "brezeln": Recipe("Brezeln", 15, 200),
    "test": Recipe("Test", 0.1, 300),

    "nudeln": Recipe("Nudeln", 10, None),
    "reis": Recipe("Reis", 20, None),
    "kartoffeln": Recipe("Kartoffeln", 25, None),
    "brokkoli": Recipe("Brokkoli", 8, None),
    "blumenkohl": Recipe("Blumenkohl", 10, None),
    "spargel": Recipe("Spargel", 15, None),
    "hot dogs": Recipe("Hot Dogs", 8, None)
}